DROP DATABASE blog;
CREATE DATABASE blog;
USE blog;

CREATE TABLE `T_USER`
(
    `USERNAME` VARCHAR(50) UNIQUE NOT NULL,
    `PASSWORD` VARCHAR(500)       NOT NULL,
    PRIMARY KEY (USERNAME)
)
    ENGINE = InnoDB
    DEFAULT CHARSET latin1;


CREATE TABLE `T_DETAIL`
(
    `ID`               INT          NOT NULL,
    `BLOG_NAME`        VARCHAR(255) NOT NULL,
    `BLOG_DESCRIPTION` VARCHAR(500) NOT NULL,
    `BLOG_DOMAIN`      VARCHAR(255) NOT NULL,
    `LINKEDIN_URL`     VARCHAR(500),
    `FACEBOOK_URL`     VARCHAR(500),
    `TWITTER_URL`      VARCHAR(500),
    `GITHUB_URL`       VARCHAR(500),
    PRIMARY KEY (ID)

)
    ENGINE = InnoDB
    DEFAULT CHARSET latin1;

CREATE TABLE `T_IMAGE`
(
    `ID`   INT(20)      NOT NULL AUTO_INCREMENT,
    `PATH` VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARSET latin1;

CREATE TABLE `T_POST`
(
    `ID`            INT(20)      NOT NULL AUTO_INCREMENT,
    `TITLE`         VARCHAR(255) NOT NULL,
    `PERMALINK`     VARCHAR(255) NOT NULL,
    `CONTENT`       TEXT         NOT NULL,
    `STATUS`        BOOLEAN      NOT NULL,
    `VIEWS`         INT(20)      NOT NULL,
    `IMAGE_ID`      INT(20)      NOT NULL,
    `CREATED_DATE`  DATE         NOT NULL,
    `MODIFIED_DATE` DATE,
    PRIMARY KEY (ID),
    CONSTRAINT FOREIGN KEY (`IMAGE_ID`) REFERENCES T_IMAGE (ID)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARSET latin1;

CREATE TABLE `T_COMMENT`
(
    `ID`      INT(20)      NOT NULL AUTO_INCREMENT,
    `NAME`    VARCHAR(255) NOT NULL,
    `CONTENT` VARCHAR(500) NOT NULL,
    `POST_ID` INT(20)      NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FOREIGN KEY (`POST_ID`) REFERENCES T_POST (ID)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARSET latin1;

INSERT INTO T_USER
VALUES ('admin', 'root');

INSERT INTO T_DETAIL VALUE (
                            '1', 'Jamith \' Blog', ' programming, linux and internet technology.', 'www.jamith.com',
                            'linkedin', 'fb', 'twitter', 'github');
